version: '3.8'
services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: moongklworks!
      MYSQL_DATABASE: mh_admin
      MYSQL_USER: root
      MYSQL_PASSWORD: moongklworks!
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mariadb_data:
  redis_data:
