server:
  port: 8080
  servlet:
    session:
      cookie:
        name: JSESSIONID
      timeout: 30m
spring:
  application:
    name: moongkl-here-admin-api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://${MARIA_HOST}:${MARIA_PORT}/${INITIAL_DB}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    url: jdbc:mariadb://localhost:${MARIA_PORT}/${INITIAL_DB}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  session:
    store-type: redis
    redis:
      flush-mode: on_save # Sessions flush mode.
      namespace: spring:session # Namespace for keys used to store sessions.

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    #database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: ${SPRING_DATASOURCE_DDL-AUTO}
      #MariaDB여도 SpringBoot3, MariaDB10.2에서 아래 설정을 사용해야함
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        format_sql: true
    repositories:
      enabled: true
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}